[package]
name = "slugrust"
version = "0.1.1"
authors = ["Ian Ker-Seymer <i.kerseymer@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
slugify = "0.1.0"
ruru = "0.9.0"

[package.metadata.thermite]
github_releases = true
